## version du format de docker compose
version: '3.8'

## version de airflow
x-airflow-common: &airflow-common
  ## image docker de airflow
  image: apache/airflow:2.9.1
  environment:
    ## pour signifier que les taches doivent touener dans le meme conteneur
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    ## adresse de la base de donnée postgres interne (base de airflow pas ma base de donnée )
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    ## clé de chiffrement pour les mots de passe
    AIRFLOW__CORE__FERNET_KEY: ''
    ## mettre en pause automatiquement les nouveau dag crées
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
    ## desactive les Das d'exemple
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    ## methode d'authentification classique pour se connecter a airflow login / mot de passe
    AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth'
    ## clé secrete pour securiser les sessions web
    AIRFLOW__WEBSERVER__SECRET_KEY: 'azerty'
    ## clé api open weather
    OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
    ## connexion a ma base de donné mon airflow a moi
    TARGET_DB_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}

  ## les vomumes font le pont entre le conteneur et mon ordi (stockages)
  ## gauche dossier sur mon ordi droite dossier dansle conteneur
  volumes:
    - ./dags:/opt/airflow/dags
    - ./plugins:/opt/airflow/plugins
    - ./logs:/opt/airflow/logs

  ## pour signifier que le contenuer doit demarré uniquement que la bd est pretre
  depends_on:
    postgres:
      condition: service_healthy

## les differents conteneurs qui vont tourner
services:

  ## ------- service 1 : PostgreSQL — Base de données interne d'Airflow
  ## Stocke : les DAGs, l'historique des runs, les users, les logs
  ## C'est PAS ta base de données métier, c'est celle d'Airflow
  postgres:
    image: postgres:15  # version de postgre
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5
    ports:
      - "5433:5432"

  ## --------SERVICE 2 : Webserver — L'interface visuelle d'Airflow
  ## Accessible sur http://localhost:8080
  ## Permet de voir les DAGs, déclencher des runs, lire les logs
  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5

  ## SERVICE 3 : Scheduler — Le cerveau d'Airflow
  ## Surveille en permanence tous tes DAGs
  ## Déclenche les tâches au bon moment selon leur planning (schedule)
  ## Sans lui, aucun DAG ne s'exécute automatiquement
  airflow-scheduler:
    <<: *airflow-common
    command: scheduler

  ## SERVICE 4 : Init — Script d'initialisation (tourne UNE SEULE fois)
  ## Prépare la base de données et crée le compte administrateur
  ## Une fois terminé, ce conteneur s'arrête tout seul (restart: "no")
  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
            --username admin
            --firstname Admin
            --lastname User
            --role Admin
            --email mthblk61@gmail.com
            --password admin
      "
    restart: "no"