# fichier docker-compose

version: '3.8'

## definition de airflow
x-airflow-common: &airflow-common
  image : apache/airflow:2.9.1

  environment:
    AIRFLOW_CORE_EXECUTOR: LocalExecutor

## connexion de airflow a sa propre base de donnée postgresql
## c'ewt que sont stockée les meta données

    AIRFLOW_DATABASE_SQL_ALCHEMY_CON: postgresql+psycopg2://airflow:airflow@postgres/airflow

    AIRFLOW_CORE_FERNET_KEY: ''
    AIRFLOW_CORE_DAGS_ARE_PAUSED_AT_CREATION: 'true'
    AIRFLOW_CORE_LOAD_EXEMPLES: 'false'
    AIRFLOW_API_AUTH_BACKENDS: 'airflow.api.auth.backend.basic.auth'
    AIRFLOW_WEBSERVER_SECRET_KEY: 'azerty'

## les variables provenant du fichier .env
    OPENWEATHER_API_KEY: ${b8aa83e138f429f02f2a613da8c9fa4a}
    TARGET_DB_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}:@${DB_HOST}:5432/${DB_NAME}

  volumes:

## ces lignes branchent les dossiers locaux dans le fichier docker
## qunad on modiifie le fichier du dag  airfloow le voit directement pas besoin de redemarrer

  - ./dags:/opt/airflow/dags
  - .plugins:/opt/airflow/plugins
  - ./logs:/opt/airflow/logs

  depends_on:
    postgres:
      condition: service_healthy  # airflow attend que postgres soit pret avant de demarrer

services:

  ## ------------------ SERVICE 1: POSTGRESQL INTERNE D'AIRFLOW ------------------------------------
  ## CECI EST LA BASE DE DONNÉE  DE AIRFLOW PAS LA MIENNE POUR STOCKER (LES DAGS,LOGS,USERS ....)

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow

    healthcheck:
      test: ["cmd", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

    ports:
      - "5433:5432" ## port 5433 sur ma machine et port 5432 dans le conteneur car postgres tourne deja sur 5432 en local

  ## --------------- SERVICE 2: INTERFACE WEB D'AIRFLOW ----------------------------------------------
  ## VISIBLE SUR HTTP://LOCALHOST:8080

  airflow-webserver:
    <<: *airflow-common   ## herite de toute la configuration definit plus haut
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      retries: 5

  # ---------------- SERVICE 3 : Scheduler Airflow -------------------------------------------------------------
  # Le cerveau d'Airflow — il surveille en permanence les DAGs
  # et déclenche les tâches au bon moment
  airflow-scheduler:
   <<: *airflow-common
   command: scheduler

  ## ---------------- SERVICE 4 : INITIALISATION  -------------------------------------------------
  ## Ce service crée les tables internes d'Airflow et le compte admin
  ## Une fois terminé, il s'arrête tout seul (restart: "no")

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db migrate &&
        airflow users create
            --username admin
            --firstname Admin
            --lastname User
            --role Admin
            --email mthblk61@gmail.com
            --password admin 
      "
    restart: no
